### PR TITLE
add python 3.5 to travis builds

### PR DESCRIPTION
**Pull request by dzen**
refs #50 issue.

### CODE REVIEW

**Comment by leth** [comment]
Looking into the test failures, there seems to be some problem in pyrabbit's use of urllib2 on python 3.5.
Pyrabbit master has switched to requests instead of urllib2, which should fix the problem.
watch out for the small rabbitmq API url change!

**Comment by dzen** [comment]
hello @leth 

yes exactly, but we often rely on project releases :/
I think pyrabbit probably should rely on requests since the httplib2 maintainer just give up maintaining another http lib: http://bitworking.org/news/2016/03/an_update_on_httplib2

**Comment by leth** [comment]
You could instead use pyrabbit from git instead of httplib2!

**Comment by dzen** [comment]
Got it now :  Latest commit 5630e73 on Dec 24, 2015 @bkjones bkjones Replace httplib2 with requests

**Comment by dzen** [comment]
Seems that this pyrabbit version calls /vhosts/<name> instead of /api/vhosts/<name>

digging.

**Comment by leth** [comment]
Yep; the string you give to pyrabbit has changed from `localhost:port` to `localhost:port/api`.
I think I saw it in the readme.

**Comment by leth** [comment]
Ah you already found that!

**Comment by dzen** [comment]
Do you mind if I ask you to test it a little bit on python 3.5 ?  I mean, if you have a larger project.

**Comment by dzen** [comment]
I rebase, and I'm ready to push this on master.

**Comment by leth** [comment]
Thanks!
We're not quite ready to test things out immediately; we were just looking into our dependencies before we started. We'll get back to you when we get a chance to do so!

**Comment by leth** [comment]
Also: you might wish to update the classifiers in setup.py :)

**Comment by dzen** [comment]
I didn't updated the modifiers since I can't test if aioamqp works well with 3.5. I can't guarantee that

**Comment by leth** [comment]
Fair enough

**Pull request merged**
