### PR TITLE
use default ssl context when ssl is enabled

### PR DESCRIPTION
**Pull request by catlee**

### CODE REVIEW

**Comment by dzen** [comment]
hello!
Thank you for your pull request on that topic that we completely overshadowed for the moment.

How is it possible to create a few tests on this ?
Travis does not provides helpers to make rabbitmq listen on ssl connections, sadly, but we should provide a few docs on how to make rabbitmq listen for ssl connections and a few tests which won't be enabled on Travis.

**Comment by catlee** [comment]
I would love to create some tests, but am at a bit of a loss for a nice way
to do that. Perhaps setting up a local ssl proxy to connect to travis'
rabbit instance would work?

**Comment by dzen** [comment]
SSL is now integrated since https://github.com/Polyconseil/aioamqp/commit/5051b5e0a6970d86ce5cb9a80a48e44b89c48b40

**Comment by mpaolini** [comment]
we can close this one

**Pull request closed without merging**
