### PR TITLE
Python 3.10 support

### PR DESCRIPTION
**Pull request by tkukushkin**

### CODE REVIEW

**Comment by Mokto** [comment]
Any update on this please ?

**Comment by RemiCardona** [comment]
working on it, along with other PRs, to craft a new release. Can't give a specific timeframe, but it's brewing.

**Comment by RemiCardona** [comment]
I rebased and merged your PR (in 3650b99fb2e39c7335a8cecef383921f8131b73e), with minimal changes (I've dropped 3.6 support in the process, it's EOL upstream).

Thank you so much for doing all the grunt work and for your patience with us.

Cheers

**Comment by Mokto** [comment]
Thanks! Any idea when it will be released ?

**Comment by ermakov-oleg** [comment]
@RemiCardona Hi! Is there anything stopping us from releasing python version 3.10? I'd be happy to help.

**Pull request closed without merging**
