### PR TITLE
Add check for bit length  used by frame int value to write long-long-int

### LINKED ISSUE #180: Wrong conversion for message-ttl
Declaring a queue, which I know already exist, gives a 406 Precondition Failed error:
```
aioamqp.exceptions.ChannelClosed: (406, "PRECONDITION_FAILED - inequivalent arg 'x-message-ttl' for queue 'text' in vhost '/': received '-1875767295' but current is '2419200000'")
```

Seems like when I declare the queue (`2419200000` = 4 weeks in milliseconds):
```
await channel.queue_declare(
        queue_name=QUEUE, durable=True, arguments={
            'x-message-ttl': 2419200000,
            'x-max-priority': 2
        }
    )
```
it is somehow interpreted as `-1875767295`.  I found what I think is the location where it parses the `arguments` values, which is shown [here](https://github.com/Polyconseil/aioamqp/blob/master/aioamqp/frame.py#L84).

My best guess is that it is parsing the value as a signed 32 bit int, when it should be a 64 bit number, but I'm really not sure since the method used in the linked code *is* using `write_long`.

Any ideas on what is wrong?

### PR DESCRIPTION
**Pull request by Jacobh2**
This fixes #180 using [bit_length](https://docs.python.org/3/library/stdtypes.html#int.bit_length) to check if the value needs to be a `long-long-int`

### CODE REVIEW

**Comment by dzen** [comment]
yep, now with a nice test in https://github.com/Polyconseil/aioamqp/blob/master/aioamqp/tests/test_queue.py with a custom x-message-ttl would be good ?

**Comment by Jacobh2** [comment]
I've added a test which checks with a value that requires the `long-long-int` type. I tested this value with the current version and it fails as predicted.

I also updated the tests to correctly use the `self.host` and `self.port` variables, which are set using the `AMQP_HOST` and `AMQP_PORT` ENV respectively. Before it was only used in one place, and otherwise defaulted to `localhost`, which doesn't work when running the tests using Docker

**Comment by dzen** [comment]
Neat !

**Comment by Jacobh2** [comment]
Do you think this could be accepted and a new version on pypi to be released?

**Comment by dzen** [comment]
Yep, I will by the end of the week

**Pull request merged**
