### PR TITLE
Client send heartbeat periodically

### LINKED ISSUE #96: RabbitMQ heartbeat issue ([Errno 104] Connection reset by peer)
I'm using aioamqp 0.7 in python 3.5 envioronment.

About 180 seconds after I called basic_consume 

> await self.channel.basic_consume(queue_name='worker_heartbeat', callback=self.handle_heartbeat, no_ack=True)

there are error message in my terminal

```
[2016-05-07 18:39:39,461] asyncio:ERROR: Task exception was never retrieved
future: <Task finished coro=<disconnected() done, defined at /home/vagrant/Project/foo/bar/core/mq_connection.py:31> exception=AmqpClosedConnection()>
Traceback (most recent call last):
  File "/home/vagrant/venv/foo/lib/python3.5/site-packages/aioamqp/frame.py", line 413, in read_frame
    data = yield from self.reader.readexactly(7)
  File "/usr/lib/python3.5/asyncio/streams.py", line 659, in readexactly
    block = yield from self.read(n)
  File "/usr/lib/python3.5/asyncio/streams.py", line 617, in read
    yield from self._wait_for_data('read')
  File "/usr/lib/python3.5/asyncio/streams.py", line 451, in _wait_for_data
    yield from self._waiter
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 297, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/home/vagrant/Project/foo/bar/core/mq_connection.py", line 37, in disconnected
    raise exception
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 663, in _read_ready
    data = self._sock.recv(self.max_size)
ConnectionResetError: [Errno 104] Connection reset by peer

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/home/vagrant/Project/foo/bar/core/mq_connection.py", line 37, in disconnected
    raise exception
  File "/home/vagrant/venv/foo/lib/python3.5/site-packages/aioamqp/protocol.py", line 262, in run
    yield from self.dispatch_frame()
  File "/home/vagrant/venv/foo/lib/python3.5/site-packages/aioamqp/protocol.py", line 204, in dispatch_frame
    frame = yield from self.get_frame()
  File "/home/vagrant/venv/foo/lib/python3.5/site-packages/aioamqp/protocol.py", line 189, in get_frame
    yield from frame.read_frame()
  File "/home/vagrant/venv/foo/lib/python3.5/site-packages/aioamqp/frame.py", line 415, in read_frame
    raise exceptions.AmqpClosedConnection() from ex
aioamqp.exceptions.AmqpClosedConnection

```

At the same time I got error message in rabbitMQ log like:
```
=INFO REPORT==== 7-May-2016::18:36:39 ===
accepting AMQP connection <0.5469.0> (192.168.50.4:53416 -> 192.168.50.4:5672)

=ERROR REPORT==== 7-May-2016::18:39:39 ===
closing AMQP connection <0.5469.0> (192.168.50.4:53416 -> 192.168.50.4:5672):
Missed heartbeats from client, timeout: 60s
```

It seems that after 3 missing heartbeat, the rabbitMQ server close the connection.

And I notice that if nothing is published in the queue I consume, the connection will not be closed.

But in the rest part of my project, I use the same way to create channel, and consume the message, nothing seems to be wrong.

My question is: 
- How can I ensure aioamqp to send heartbeat normally? 
- Can you kindly tell me what is the possible mistake I made?

please forgive my poor English.

### PR DESCRIPTION
**Pull request by comzyh**
try to fix #96

I will remove `logger.debug` if you think it's not necessary.

### CODE REVIEW

**Comment by mpaolini** [comment]
Just had a quick look. Maybe you should cancel the heartbeat worker on shutdown?

**Comment by comzyh** [comment]
@mpaolini 

You are right. I use while loop because I can't find a method like `set_timeout` or whatever.

But maybe the condition `while self.is_open`  is enough ?

https://github.com/Polyconseil/aioamqp/pull/97/files#diff-a1512baaedd3b5456a3a9eea30fc6297R314

I make this patch reference to https://github.com/pika/pika/blob/502aa0e6fdb57274aa1583138081eefc6b6e8f62/pika/heartbeat.py#L159

**Comment by mpaolini** [comment]
tested in staging here, seems to be working OK. 

I made a small change here in this branch of mine https://github.com/Polyconseil/aioamqp/compare/master...elastic-coders:heartbeat_fix#diff-a1512baaedd3b5456a3a9eea30fc6297R315

Feel free to use or drop my own change

**Comment by comzyh** [comment]
I'm not good at English, lol. 
So, does "tested in staging" means "tested in production environment" ?

And. I can't fully understand the diff your give above, there a part of my code in that diff. 
I can see your modification in `_run_heartbeat_timer` function.

And I think your patch may bring a bug here(maybe):

> I also add  small enhancement to log a warning if the server does not reply to our own hearbeats

pay attention to this line https://github.com/elastic-coders/aioamqp/commit/53a6c89a04aa02c7c82319ace78d9fdf0570c8ea?diff=unified#diff-a1512baaedd3b5456a3a9eea30fc6297R315

Based on my understand of RabbitMQ heartbeat protocol, Server and Client just have to send a heartbeat  before *last_heartbeat_time +  timeout*.

And. Server **don't have to** send a heartbeat as a reply of heartbeat from client **immediately**. 
**(IMPORTANT 1)**

In this line, you set `timeout=self.server_heartbeat / 2`, so a server working correctly my not send a heartbeat in *timeout / 2* seconds. 

so your code may raise **false-alarm**

Then your code may bring in another bug.

Based on **IMPORTANT 1**, `heartbeat` function may finish(this is a coroutine. i cant find better word, maybe 'return'?) after a few seconds(let it be _t1_), so the interval of heartbeat may be increased by _t1_, i think that's not right.

I'm looking forward to your reply.

**Comment by mpaolini** [comment]
@comzyh 

> So, does "tested in staging" means "tested in production environment" ?

It means that is running on our servers but only for developers and internal testers to enjoy

> Based on IMPORTANT 1, heartbeat function may finish(this is a coroutine. i cant find better word, maybe 'return'?) after a few seconds(let it be t1), so the interval of heartbeat may be increased by t1, i think that's not right.

rightly so, my patch can definitely delay the client heartbeat.

Keep in mind that `hearbeat()` does return everytime a message is received from server. Not just when a heartbeat is received.

In my patch I just tried to point out that we might need some modification to the current `._heartbeat_waiter` and `.heartbeat()` functions. But your patch is valid even without those.

please @dzen merge this ;)

**Comment by mpaolini** [comment]
@comzyh as a matter of facts, I do see sporadic warnings in staging using my own patch, so it is not good

**Comment by RemiCardona** [comment]
I'm not exactly thrilled about the patches here, though I agree they do improve the poor state of the heartbeat feature as a whole.

I'll try to come up with a patch soon (today or tomorrow) and I'll run it by you guys. @mpaolini I'd be grateful if you could give it a spin as well.

Thanks to both of you for the patches and your patience, it's greatly appreciated.

**Comment by comzyh** [comment]
> Keep in mind that hearbeat() does return everytime a message is received from server. Not just when a heartbeat is received.

@mpaolini I do forget this, thank you.

**Comment by RemiCardona** [comment]
PR #96 was merged, closing this one. Thanks again for the tests and your patience.

Cheers

**Comment by comzyh** [comment]
Cheers

**Pull request closed without merging**
