### PR TITLE
Updated AmqpEncoder

### PR DESCRIPTION
**Pull request by MegaDiablo**
Added support of array, datetime, float, decimal and None value. Added converting timestamp to datetime

### CODE REVIEW

**Comment by dzen** [comment]
Hello @MegaDiablo.

Thank you for this PR. It's right, we're missing the `field-array` frame type.

Since the code looks okay, would you please add a test ?
Furthermore we probably want to have the `AmqpDecoder` class to implement such fonctionnality haven't we ?

**Comment by MegaDiablo** [comment]
Hi @dzen.

Class `AmqpDecoder` have support `field-array` frame type.
 (https://github.com/Polyconseil/aioamqp/blob/master/aioamqp/frame.py#L321)

**Comment by dzen** [comment]
Woops, sorry :D

**Comment by MegaDiablo** [comment]
Hi @dzen 

Look this upgrade of `AmqpEncoder `. In `AmqpDecoder` all this types was implimented before me

**Comment by RemiCardona** [comment]
@MegaDiablo thanks a lot for your PR, it's greatly appreciated!

Cheers

**Pull request merged**
